# config.yaml
# to install yaml: conda install -c anaconda pyyaml
# ==========================================================================================
# 1. General Configuration
# ==========================================================================================
# General settings for the entire project
generalSettings:
  # Directories
  directories:
    dataPath: "./data" # data path
    processedDataPath: "./data/processed" # processed data path
    sharedObjectsPath: "./cFiles" # shared objects path
    logPath: "./logs" # log path

  # Logging settings
  logging:
    silentMode: false # if true, suppresses console output
    logLevel: "RESULTS" # log level to save to log file, options: "NONE", "CONSOLE", "RESULTS", "SIMPLE"

  # system settings
  system:
    highRAMSystem: false # if true, uses high RAM system settings



# ==========================================================================================
# Data Pre-processing Configuration
# ==========================================================================================
preProcessingConfig:
  # General settings
  general:
    downloadData: true # if true, downloads data from the source
    deleteWhenDone: true # if true, deletes downloaded files after processing

  # ======================================================================================
  # 2.1 Swift BAT Configuration
  # ======================================================================================
  # Configuration for Swift BAT data pre-processing
  swiftBATConfig:
    # Download settings
    download:
      energyRange: "15-350" # energy range
    
    # Processing settings
    processing:
      initialBinSize: 100e-6 # initial bin size


  # ======================================================================================
  # 2.2 Fermi GMB Configuration
  # ======================================================================================
  # Configuration for Fermi GMB data pre-processing

  # placeholder for future Fermi GMB configuration settings change values later
  fermiGMBConfig:
    # Download settings
    download:
      energyRange: "8-1000" # energy range
    
    # Processing settings
    processing:
      initialBinSize: 100e-6 # initial bin size

  # ======================================================================================
  # 2.3 SVOM Configuration
  # ======================================================================================
  # Configuration for SVOM data pre-processing
  SVOMConfig:
    # Download settings??? Not sure if SVOM will have a download portal?
    download:
      energyRange: "15-350" # energy range
    
    # Processing settings
    processing:
      initialBinSize: 100e-6 # initial bin size

  # placeholder for future SVOM configuration settings change values later


# ==========================================================================================
# 3. MVT Analysis Configuration
# ==========================================================================================
mvtAnalysisConfig:
  # Analysis settings
  timeWindowSize: 0.3 # time window size for MVT analysis
  signalToNoiseThreshold: 5.0 # signal-to-noise threshold
  significanceSigmaThreshold: 3.0 # significance sigma threshold for power over background noise

  haarDenoiseSettings:
    # Threshold settings
    thresholdSoft: False # if true, uses soft thresholding; if false, uses hard thresholding
    thresholdScaleFactor: 1.0 # scale factor for threshold coefficients
    estimateNoise: False # if true, estimates noise from the data

  haarNDWTSettings:
    # NDWT settings
    
  

