"""
code expects a file name string as an argument
likely only to work on linux?
"""

import pexpect
from swiftBATCatalogueGRB import importData, getCoordinates, getStartStopTime


# function to open an shell terminal and process the data using the HEASoft tools
def processSwiftBATData(
        filename: str,
        SNRThreshold: float,
        energyBins: str,
        GRBName: str,
        timeDeliniation: float = 0.0
        ) -> None:
    """_summary_

    Args:
        filename (str): relative path to the data file to be processed. The directory should is seperated from the file name by the function. It is expected that the data is in the format/structure retrevied from the Swift data archive from one of its autogenerated wget commands.
        timeDeliniation (float): time delineation for the light curve
        energyBins (str): energy bins for the light curve needs to be a string in the format "15-350" for 15-350 keV. Run multiple times with different energy bins to get light curves for different energy ranges. As per the swift BAT documentation, the energy  range of the BAT sensor is 15-350 keV.
        GRBName (str): the name of the GRB to be processed. Fomatted as "GRBYYMMDDX", where X is the letter assigned to the GRB. This is used to find the coordinates and start/stop time of the GRB from the catalogue.
    Example:
    >>> processSwiftBATData('data/reproc/00306757000/bat/event/sw00306757000bevshsp_uf.evt.gz', 1.0, "15-350")
    """
    # helper functions
    # function to unzip a file if it is compressed
    def unzipFile(shell: pexpect.spawn, file: str) -> None:
        # gunzip sw*.evt.gz
        shell.sendline(f'gunzip sw*.evt.gz')
        shell.expect(f'{file[:-3]}')


    # function to zip a file if it is uncompressed
    def zipFile(shell: pexpect.spawn, file: str) -> None:
        # gzip sw*.evt
        shell.sendline(f'gzip sw*.evt -v')
        shell.expect(f'{file}', timeout=None) # this can take a while, so set the timeout to None


    # function to check if the gain correction has been applied to the data
    def checkGainCorrection(shell: pexpect.spawn, file: str) -> bool:
        print("Checking gain correction")
        shell.sendline(f'fkeyprint {file} GAIN')
        shell.expect('GAINAPP')
        with open('shellOutput.txt', 'r') as f:
            lines: list[str] = f.readlines()
        bools: list[bool] = []
        # There should be:
        # GAINAPP = T / Gain correction has been applied
        # GAINMETH= 'FIXEDDAC' / Cubic ground gain/offset correction using DAC-b
        for line in lines:
            if line.startswith('GAINAPP'):
                if 'T' in line or "Gain correction has been applied" in line:
                    bools.append(True)
                else:
                    bools.append(False)
            if line.startswith('GAINMETH'):
                if 'FIXEDDAC' in line:
                    bools.append(True)
                else:
                    bools.append(False)
        # if both checks pass, return True, otherwise return False
        if all(bools):
            print("Gain correction already applied")
        return all(bools)


    # function to apply the gain correction to the data
    def correctGain(shell: pexpect.spawn, file: str) -> None:
        print("Applying gain correction")
        # if the file is compressed, uncompress it
        if file.endswith('.gz'):
            unzipFile(shell, file)

        ##########################################################################################
        # THIS NEEDS WORK! Not all of the data sets have a gain/offset map. The calfile= argument
        # may return an error if there is no gain/offset map. See 5.3.5 of the BAT analysis guide
        # for more details.
        ##########################################################################################


        # apply the gain correction
        #     bateconvert infile=sw00306757000bevshsp_uf.evt calfile=../hk/sw00306757000bcbo01deg00ab.fits.gz residfile=CALDB pulserfile=CALDB fitpulserfile=CALDB outfile=NONE calmode=INDEF
        shell.sendline(f'bateconvert infile={file[:-3]} calfile=../hk/{file.split("sw")[1].split("bev")[0]}bcbo01deg00ab.fits.gz residfile=CALDB pulserfile=CALDB fitpulserfile=CALDB outfile=NONE calmode=INDEF')
        shell.expect('bateconvert')
        # rezip the file
        zipFile(shell, file)
        

    # function to check the mask weighting and version of the HEASoft tools
    def checkMask(shell: pexpect.spawn, file: str) -> None:
        # helper function to check if the mask weighting has been applied to the data
        def checkMaskWeighting() -> bool:
            with open('shellOutput.txt', 'r') as f:
                lines: list[str] = f.readlines()
            bools: list[bool] = []
            # a. check if the data has a mask weighting
            # There should be something like:
            #   BAT_RA = 320.5402 / [deg] Right ascension of source
            # BAT_DEC = 77.0751 / [deg] Declination of source
            for line in lines:
                if line.startswith('BAT_RA'):
                    splitLine: str = line.split('=')[1].strip().split('/')[0].strip()
                    try:
                        float(splitLine)
                        bools.append(True)
                    except :
                        bools.append(False)
                if line.startswith('BAT_DEC'):
                    splitLine: str = line.split('=')[1].strip().split('/')[0].strip()
                    try:
                        float(splitLine)
                        bools.append(True)
                    except :
                        bools.append(False)
                # This should potentially also check if the position is correct.
            
            if all(bools):
                print("Mask weighting already applied")
            # if all checks pass, return True, otherwise return False
            return all(bools)


        # helperfunction to check the version of the HEASoft tools is > 6.1.2
        def checkMaskVersion() -> bool:
            with open('shellOutput.txt', 'r') as f:
                lines: list[str] = f.readlines()
            bools: list[bool] = []
            # b. check the version of the HEASoft tools > 6.1.2
            # There should be something like:
            # BATCREAT= 'batmaskwtevt 1.11' / BAT Program that modified this FITS file
            version: float = 0.0
            for line in lines:
                if line.startswith('BATCREAT'):
                    if 'batmaskwtevt' in line:
                        version: float = float(line.split('batmaskwtevt')[1].strip().split(' ')[0].strip('\''))
                        if version > 1.16:
                            bools.append(True)
                        else:
                            bools.append(False)
                    else:
                        bools.append(False)
            
            if all(bools):
                print(f"batmaskwtevt version is {version}")
            # if the check passes, return True, otherwise return False
            return all(bools)


        print("Checking mask weighting and HEASoft version")
        # 4. Check if the data has a mask weighting and the version of the HEASoft tools is > 6.1.2
        #     fkeyprint {filename} BAT_
        shell.sendline(f'fkeyprint {file} BAT_')
        shell.expect('BAT_RA')
        bools: list[bool] = []
        # check if there is a weighting
        if checkMaskWeighting():
            bools.append(True)
        else:
            bools.append(False)
        shell.sendline(f'fkeyprint {file} BATCREAT')
        shell.expect('FILE')
        # check the version of the HEASoft tools > 6.1.2 (looking for batmaskwtevt version > 1.16)
        if checkMaskVersion():
            bools.append(True)
        else:
            bools.append(False)
        
        return all(bools)


    # function to apply the mask weighting to the data
    def correctMask(
            shell: pexpect.spawn,
            file: str,
            data: list[list[str]]
            ) -> None:
        # if the file is compressed, uncompress it
        if file.endswith('.gz'):
            unzipFile(shell, file)
        # find the coordinates of the GRB from the catalogue
        trigID: str = file.split("sw")[1].split("bev")[0].strip('0')
        ra, dec = getCoordinates(trigID, data)
        print(trigID)
        # apply the mask weighting
            # batmaskwtevt infile={unzipped file} attitude=../../auxil/sw00306757000sat.fits.gz ra=320.5397083 dec=+77.074861 detmask=../hk/sw00306757000bdqcb.hk.gz rebalance=YES corrections=default auxfile=/local/data/gcn5b/craigm/sw00306757000bevtr.fits clobber=YES
            # This can take several minutes per file.
        shell.sendline(f'batmaskwtevt infile={file[:-3]} attitude=../../auxil/sw{file.split("sw")[1].split("bev")[0]}sat.fits.gz ra={ra} dec={dec} detmask=../hk/{file.split("sw")[1].split("bev")[0]}bdqcb.hk.gz rebalance=YES corrections=default auxfile=/local/data/gcn5b/craigm/{file.split("sw")[1].split("bev")[0]}bevtr.fits clobber=YES')
        print(f'batmaskwtevt infile={file[:-3]} attitude=../../auxil/sw{file.split("sw")[1].split("bev")[0]}sat.fits.gz ra={ra} dec={dec} detmask=../hk/{file.split("sw")[1].split("bev")[0]}bdqcb.hk.gz rebalance=YES corrections=default auxfile=/local/data/gcn5b/craigm/{file.split("sw")[1].split("bev")[0]}bevtr.fits clobber=YES')
        shell.expect('batmaskwtevt v')
        shell.expect('ERROR')


        ##########################################################################################
        # THIS NEEDS WORK! Not all of the data sets have a gain/offset map. The calfile= argument
        # may return an error if there is no gain/offset map. See 5.3.5 of the BAT analysis guide
        # for more details.
        ##########################################################################################



        # rezip the file
        zipFile(shell, file)    



    # inital processing steps
    # 1. navigate to the directory where the data is eg cd 00306757000/bat/event
    # split the file name into a directory and a file name
    directory, file = filename.rsplit('/', 1)
    print("Opening shell terminal")
    shell = pexpect.spawn("sh", encoding='utf-8')
    logFile = open('shellOutput.txt', 'w')
    shell.logfile_read = logFile
    shell.sendline(f'cd {directory}')
    shell.expect(f'{directory}.*') # wait for the prompt to change to the new directory

    # 2. initilaise the HEASoft tools
    print("Initialising HEASoft tools")
    shell.sendline('source $CALDB/software/tools/caldbinit.sh')
    shell.expect('CALDB/software/tools/caldbinit.sh') 
    shell.sendline('source $HEADAS/headas-init.sh')
    shell.expect('headas-init.sh')



    # 3. Check if the data has the correct energy scale
    if not checkGainCorrection(shell, file):
        correctGain(shell, file)

    # 4. Check if the data has a mask weighting and the version of the HEASoft tools is > 6.1.2
    data, _ = importData('summary_general.csv')
    if not checkMask(shell, file):
        correctMask(shell, file, data)

    # 5. Extract the light curve from the data
    print("Extracting light curve")
    # find the start and stop time of the GRB from the catalogue

    startTime, stopTime, t90Error = getStartStopTime(GRBName, data)
    print(f"Start time: {startTime}, Stop time: {stopTime}, T90 error: {t90Error}")
    # if the time deliniation is 0, use the SNR to determine the time bins
    if timeDeliniation != 0.0:
        timebinalg: str = "u"
        timeDeliniationString: str = f"timedel={timeDeliniation} "
    else:
        timeDeliniationString = f"snrthresh={SNRThreshold} "
        timebinalg: str = "snr"
    # batbinevt infile={filename} outfile=onesec.lc outtype=LC timedel=1.0 timebinalg=u energybins=15-150 detmask=../hk/sw00306757000bdqcb.hk.gz clobber=YES
    lightCurveCommand: str = f'batbinevt infile={file[:-3]} outfile=output.lc outtype=LC {timeDeliniationString}timebinalg={timebinalg} energybins={energyBins} detmask=../hk/sw{file.split("sw")[1].split("bev")[0]}bdqcb.hk.gz tstart={startTime} tstop={stopTime} clobber=YES'
    shell.sendline(lightCurveCommand)
    if timebinalg == "snr":
        shell.expect('Histogram')
        shell.send('\n')
    shell.expect('batbinevt v')
    shell.expect(['ERROR', 'written'])
    shell.expect('----')

    # Close the shell terminal
    print("Closing shell terminal")
    shell.close()


if __name__ == "__main__":
    filename = 'data/reproc/00306757000/bat/event/sw00306757000bevshsp_uf.evt.gz'
    SNRThreshold = 5.0
    energyBins = "15-350"
    processSwiftBATData(filename, SNRThreshold, energyBins, "GRB080319B")