from analysisTools.importLightCurve import LightCurveData
from analysisTools.haarDenoise import haarDenoise
from concurrent.futures import ThreadPoolExecutor
from os import cpu_count
from numpy import ndarray, zeros, sqrt, std, random
from copy import copy
from tqdm import tqdm


class MonteCarloUncertainty:
    """
    A class to calculate the uncertainty of the denoised light curve using a parametric Monte Carlo method. The uncertainty is calculated by generating synthetic light curves based on the original light curve data and its propagated error, and then calculating the denoised values for each synthetic light curve. The standard deviation of the denoised values from the synthetic light curves is used as the uncertainty of the denoised light curve.

    Attributes:
        data (LightCurveData): The light curve data for which to calculate the uncertainty.
        numSimulations (int): The number of synthetic light curves to generate for the Monte Carlo simulation.
    """

    def __init__(
            self,
            data: LightCurveData,
            denoisedDataArgs: dict,
            numSimulations: int = 1000,
            highRAMSystem: bool = False
        ) -> None:
        """
        Initializes the MonteCarloUncertainty class with the given light curve data and number of simulations.

        Args:
            data (LightCurveData): The light curve data for which to calculate the uncertainty.
            denoisedDataArgs (dict): Arguments for the denoised data.
            numSimulations (int, optional): The number of synthetic light curves to generate for the Monte Carlo simulation. Defaults to 1000.
            highRAMSystem (bool, optional): Whether the system has high RAM available for storing synthetic light curves. Defaults to False.
        """
        self.__data: LightCurveData = data
        self.__denoisedDataArgs: dict = denoisedDataArgs
        self.__numSimulations: int = numSimulations
        self.__maximumSyntheticLightCurves: int = min(100, numSimulations) if not highRAMSystem else min(10000, numSimulations)
        self.__preBustSTD: float = std(data.preBurstData['rate'].to_numpy())
        print("Denoising the light curve data...")
        self.__poissonMean: ndarray = haarDenoise(
            self.__data,
            **self.__denoisedDataArgs
            )
        self.__lengthOfCurve: int = len(self.__poissonMean)
        self.__std: ndarray = self.__calculateUncertainty()
        data.burstData['error'] = self.__std
        data.burstData['denoisedRate'] = self.__poissonMean


    def __generateSyntheticLightCurves(
            self,
            numberOfCurves: int
            ) -> ndarray:
        """
        Generates a synthetic light curve based on the assumption that the initial denoising is the Poisson mean of the true signal. The synthetic light curve is generated by drawing random samples from a Poisson distribution with the mean equal to the denoised light curve values.

        Returns:
            ndarray: A synthetic light curve generated from the Poisson distribution.
        """
        randomGenerator: random.Generator = random.default_rng()
        arrayShape: tuple[int, int] = (numberOfCurves, self.__lengthOfCurve)
        syntheticLightCurves: ndarray = randomGenerator.poisson(
            lam = self.__poissonMean,
            size = arrayShape
            )
        
        gaussianNoise: ndarray = randomGenerator.normal(
            loc = 0,
            scale = self.__preBustSTD,
            size = arrayShape
        )
        
        return syntheticLightCurves + gaussianNoise


    def __calculateUncertainty(
            self
            ) -> ndarray:
        """
        Calculates the uncertainty of the denoised light curve using a parametric Monte Carlo method.

        Returns:
            ndarray: The uncertainty of the denoised light curve, calculated as the standard deviation of the denoised values from the synthetic light curves.
        """
        print(f"Calculating uncertainty using {self.__numSimulations} Monte Carlo simulations...")
        # calculate the number of batches needed to generate all synthetic light curves
        numBatches: int = self.__numSimulations // self.__maximumSyntheticLightCurves
        remainder: int = self.__numSimulations % self.__maximumSyntheticLightCurves
        if remainder > 0:
            numBatches += 1
        
        totalSignalSum: ndarray = zeros(self.__lengthOfCurve)
        totalSignalSquaredSum: ndarray = zeros(self.__lengthOfCurve)

        with tqdm(total = self.__numSimulations, desc = "Monte Carlo simulations", unit = "sim") as progressBar:
            for batchNumber in range(numBatches):
                # determine the number of synthetic light curves to generate in this batch
                if batchNumber == numBatches - 1 and remainder > 0:
                    numberOfCurves: int = remainder
                else:
                    numberOfCurves: int = self.__maximumSyntheticLightCurves
                
                # generate the synthetic light curves for this batch
                syntheticLightCurves: ndarray = self.__generateSyntheticLightCurves(numberOfCurves)
                
                # denoise each synthetic light curve in parallel without materializing the full output batch
                batchSignalSum: ndarray = zeros(self.__lengthOfCurve)
                batchSignalSquaredSum: ndarray = zeros(self.__lengthOfCurve)
                maxWorkers: int = cpu_count() or 1
                if maxWorkers > 1:
                    with ThreadPoolExecutor(max_workers = maxWorkers) as executor:
                        for denoisedSyntheticLightCurve in executor.map(
                            self.__denoiseSyntheticLightCurve,
                            syntheticLightCurves,
                            chunksize = 1
                        ):
                            batchSignalSum += denoisedSyntheticLightCurve
                            batchSignalSquaredSum += denoisedSyntheticLightCurve ** 2
                            progressBar.update(1)
                else:
                    for syntheticLightCurve in syntheticLightCurves:
                        denoisedSyntheticLightCurve: ndarray = self.__denoiseSyntheticLightCurve(syntheticLightCurve)
                        batchSignalSum += denoisedSyntheticLightCurve
                        batchSignalSquaredSum += denoisedSyntheticLightCurve ** 2
                        progressBar.update(1)
                
                # calculate the batch sums for each time bin
                totalSignalSum += batchSignalSum
                totalSignalSquaredSum += batchSignalSquaredSum
        
        # calculate the mean and standard deviation of the denoised synthetic light curves
        signalMean: ndarray = totalSignalSum / self.__numSimulations
        signalVariance: ndarray = (totalSignalSquaredSum / self.__numSimulations) - (signalMean ** 2)
        signalStdDev: ndarray = sqrt(signalVariance)

        print("Uncertainty calculation complete.")
        return signalStdDev


    def __makeSyntheticData(
            self,
            syntheticRate: ndarray
            ) -> LightCurveData:
        """Creates a lightweight copy of the original light curve data with a synthetic burst rate."""
        syntheticData: LightCurveData = copy(self.__data)
        syntheticData.burstData = self.__data.burstData.copy()
        syntheticData.preBurstData = self.__data.preBurstData.copy()
        syntheticData.burstData['rate'] = syntheticRate
        return syntheticData


    def __denoiseSyntheticLightCurve(
            self,
            syntheticRate: ndarray
            ) -> ndarray:
        syntheticData: LightCurveData = self.__makeSyntheticData(syntheticRate)
        return haarDenoise(
            syntheticData,
            **self.__denoisedDataArgs
        )


if __name__ == "__main__":
    data: LightCurveData = LightCurveData("GRB080319B")
    denoisedDataArgs: dict = {
        "thresholdMethod": "hard",
        "thresholdScaleFactor": 0.5
    }
    MonteCarloUncertainty(
        data = data,
        denoisedDataArgs = denoisedDataArgs,
        numSimulations = 500,
        highRAMSystem = False
    )
    