#ifndef PERMUTEANALYSIS_HPP
#define PERMUTEANALYSIS_HPP

#include <atomic>
#include <vector>

/**
 * The PermuteAnalysis class takes pointers from a Python ctypes handler and generates evenly spaced bins in delta t from a cyclic permutation Haar wavelett analysis of a given GRB light curve. This class does not handle the actuall Haar coefficient generation, that is done by the HaarCoefficient class. Instead, it handels the cyclic permutations of the dataset and the binning of results.
 */
class PermuteAnalysis
{
    public:
        // data members

        std::vector<double> logBinEdges;
        std::vector<double> logBinCenters;
        std::vector<double> powerSetAverages;
        std::vector<double> powerSetStdDevs;



        /**
         * Constructs a PermuteAnalysis object with the given data arrays and parameters.
         * @param rateArray Pointer to an array of rate values.
         * @param timeArray Pointer to an array of time values.
         * @param rateErrArray Pointer to an array of rate error values.
         * @param lenghtOfData The length of the data arrays.
         * @param numberOfTimeBins The number of time bins to use for the analysis.
         * @param burst A boolean indicating whether the analysis is for a burst or pre-burst.
         * @param preBurstPowerSetStds Pointer to an array of pre-burst power set standard deviations.
         */
        PermuteAnalysis
        (
            double *rateArray,
            double *timeArray,
            double *rateErrArray,
            int lenghtOfData,
            int numberOfTimeBins,   
            bool burst,
            double *preBurstPowerSetStds
        );

        void runAnalysis();

        int getPermutationsCompleted() const;

        int getTotalPermutations() const;

        bool isAnalysisComplete() const;


    private:
        /// data members
        std::vector<double> rate;
        std::vector<double> time;
        std::vector<double> rateErr;
        std::vector<double> timeInBins;
        int lengthOfData;
        int numberOfTimeBins;
        int kMax = 0;
        std::vector<int> kSet;
        int kSetSize = 0;
        std::vector<double> powerSetSums;
        std::vector<double> powerSetSumSquares;
        std::vector<int> powerSetCounts;
        std::atomic<int> permutationsCompleted{0};
        int totalPermutations = 0;
        std::atomic<bool> analysisComplete{false};
        std::vector<double> preBurstPowerSetStdDev;
        bool burst;


        // private member functions
        /**
         * Finds the maximum value of k based on the length of the data. Sets the kMax member variable to the largest power of 2 that is less than or equal to the length of the data.
         */
        void findKMax();


        /**
         * Finds the set of k values based on the maximum value of k. Sets the kSet member variable to a vector containing the powers of 2 from 1 to kMax. 
         */
        void findKSet();


        /**
         * Generates the output bins for the analysis. This function calculates the log of the minimum and maximum time values in the time vector, and generates a vector of evenly spaced values between these two values. The logBinEdges and logBinCenters member variables are then populated based on these values.
         */
        void generateOutputBins();


        /**
         * Calculates the time contained in each of the bins of the dataset. 
         */
        void getTimeInBins();


        /**
         * Generates a permutation of the dataset based on the given index. This function creates a new vector of rate values that is a permutation of the original rate vector, based on the given index. The permutation is generated by shifting the original rate vector by the given index, wrapping around to the beginning of the vector as necessary.
         * @param index The index of the permutation to generate.
         * @return A vector containing the permuted rate values.
         */
        std::vector<std::vector<double>> shiftData
        (
            int index
        );



        /**
         * Generates a permutation of the dataset based on the given index and runs the MVTAnalysis on it. This is done in a function to allow for multithreading, to ensure that the larger datasets are confined to the function's scope and get deleted when the function is finished, and to keep the code clean.
         * @param index The index of the permutation to generate.
         * @return A vector containing the results of the MVTAnalysis.
         */
        std::vector<std::vector<double>> analysePermutation
        (
            int index
        );


        /**
         * Bins the results of a single permutation. This function takes the results of a single permutation and bins them into the output bins generated by the generateOutputBins function. The power values for each bin are stored as a vector to be averaged over once the permutations are complete.
         * @param results The results of the permutation.
         */
        void binResults
        (
            const std::vector<std::vector<double>>& results,
            std::vector<double>& powerSums,
            std::vector<double>& powerSumSquares,
            std::vector<int>& powerCounts
        ) const;


        /**
         * Finds the average power in each bin.
         */
        void findAveragePowerInBins();


        /**
         * Finds the standard deviation of the power in each bin.
         */
        void findStdDevOfPowerInBins();




        /**
         * Manages multithreading and runs the MVTAnalysis on each permutation of the dataset.
         * @return A vector of vectors containding the average and standard deviation of the VT values for each value of k in the kSet.
         */
        void runMVTAnalysisOnPermutations();

};

#endif // PERMUTEANALYSIS_HPP