#ifndef PERMUTEANALYSIS_HPP
#define PERMUTEANALYSIS_HPP

#include <vector>

// PermuteAnalysis class declaration
class PermuteAnalysis
{
    public:
        // data members
        std::vector<double> rate;
        std::vector<double> time;
        std::vector<double> rateErr;
        std::vector<double> timeInBins;
        int lengthOfData;
        int kMax;
        std::vector<int> kSet;
        std::vector<double> VTSet;
        double* VTSetArray;
        int kSetSize;
        std::vector<double> deltaT;
        std::vector<double> deltaTError;


        /**
         * Constructs a PermuteAnalysis object with the given data arrays and parameters.
         * @param rateArray Pointer to an array of rate values.
         * @param timeArray Pointer to an array of time values.
         * @param rateErrArray Pointer to an array of rate error values.
         * @param lenghtOfData The length of the data arrays.
         * @param numberOfUniformKValues The number of uniformly spaced k values to generate. If 0, a default set of k
         * values will be used.
         */
        PermuteAnalysis
        (
            double *rateArray,
            double *timeArray,
            double *rateErrArray,
            int lenghtOfData,
            int numberOfUniformKValues = 0
        );


    private:
        // private member functions
        /**
         * Finds the maximum value of k based on the length of the data. Sets the kMax member variable to the largest
         * power of 2 that is less than or equal to the length of the data.
         */
        void findKMax();


        /**
         * Finds the set of k values based on the maximum value of k. Sets the kSet member variable to a vector 
         * containing the powers of 2 from 1 to kMax. 
         */
        void findKSet();


        /**
         * Generates a uniform set of k values based on a user-defined number of k values to generate. The k values are
         * generated on a log scale between 1 and kMax. Sets the kSet member variable to a vector containing the
         * uniformly spaced k values. This function replaces the generateEvenKSet function in the MVTAnalysis class, if
         * a non-zero value is passed to the generateUniformKSetFlag parameter in the constructor.
         */
        void generateUniformKSet
        (
            int numberOfUniformKValues
        );


        /**
         * Calculates the time contained in each of the bins of the dataset. 
         */
        void getTimeInBins();


        /**
         * Generates a permutation of the dataset based on the given index. This function creates a new vector of rate
         * values that is a permutation of the original rate vector, based on the given index. The permutation is
         * generated by shifting the original rate vector by the given index, wrapping around to the beginning of the
         * vector as necessary.
         * @param index The index of the permutation to generate.
         * @return A vector containing the permuted rate values.
         */
        std::vector<std::vector<double>> shiftData
        (
            int index
        );



        /**
         * Generates a permutation of the dataset based on the given index and runs the MVTAnalysis on it. This is done
         * in a function to allow for multithreading, to ensure that the larger datasets are confined to the function's
         * scope and get deleted when the function is finished, and to keep the code clean.
         * @param index The index of the permutation to generate.
         * @return A vector containing the results of the MVTAnalysis.
         */
        std::vector<double> analysePermutation
        (
            int index
        );


         
        /**
         * Manages multithreading and runs the MVTAnalysis on each permutation of the dataset.
         * @return A vector of vectors containding the average and standard deviation of the VT values for each value of
         * k in the kSet.
         */
        std::vector<std::vector<double>> runMVTAnalysisOnPermutations();

};

#endif // PERMUTEANALYSIS_HPP